### ISSUE TITLE
Cannot download dependency

### ISSUE THREAD

**Issue by mariussoutier** [leon/play-enumeration#1]
Hi,

I cannot use your great plug-in as an SBT dependency because it's not in the repositories.

Cheers
- Marius

**Comment by leon** [comment]
The plugin was available as a 1.0-SNAPSHOT, but I've now released version 1.0 and it should be making it's way to maven central.

**Comment by mariussoutier** [comment]
Still get this error:

```
:: se.radley#play-plugins-enumeration_2.9.1;1.0: not found
```

**Comment by leon** [comment]
It was built against Play 2.0.1.

I've releases v1.0.1 that is built against Play 2.0.2 which should fix your problem

**Comment by mariussoutier** [comment]
Tack!
